// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDInP8DgAsxn6p_WKlOoc_wjQ11EuuWenk',
    appId: '1:976784478319:android:7547fa030dc65944943d9a',
    messagingSenderId: '976784478319',
    projectId: 'testapp-ac4c3',
    databaseURL: 'https://testapp-ac4c3-default-rtdb.firebaseio.com',
    storageBucket: 'testapp-ac4c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6NaqImv29O-MRDSN7iVRzmCZyPuW13GI',
    appId: '1:976784478319:ios:7cbebdc082f218c3943d9a',
    messagingSenderId: '976784478319',
    projectId: 'testapp-ac4c3',
    databaseURL: 'https://testapp-ac4c3-default-rtdb.firebaseio.com',
    storageBucket: 'testapp-ac4c3.firebasestorage.app',
    androidClientId: '976784478319-rdsb2g4isvoftm03pt6ngm6p5scl9ulv.apps.googleusercontent.com',
    iosClientId: '976784478319-2h10d9pgdi5ea6bv1krg0bka6ttcl7ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.agence',
  );
}
